// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugsvremrwtqflqsmqjfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnc3ZyZW1yd3RxZmxxc21xamZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjA1OTcsImV4cCI6MjA2MzMzNjU5N30.6jDDRZZaPd4Q5-ovtDQwzoA8dHMGZhSlnDAfzL6qyMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);